---
- name: Install tar
  become: yes
  apt: 
    name: 
      - tar
      - unzip
    state: latest

- name: Add User 
  user: 
    name: "{{user}}" 
    shell: /bin/bash 
    append: yes
  when: add_user


- name: Check Public Key
  shell: "ls /home/{{ user }}/.ssh|grep '.pub' |wc -l"
  register: key_exist
  ignore_errors: true

- name: Generate Public key
  user:
    name: "{{ user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: "key_exist.stdout == '0' and generate_key"    

- name: Get Lastest Public From Hadoop Master
  fetch: 
    src: /home/{{ user }}/.ssh/id_rsa.pub
    dest: /tmp/id_{{ ansible_host }}_{{ user }}.pub
    flat: yes
  when: role == "master"

- name: Add Hadoop Public Key 
  authorized_key: 
    user={{ user }} 
    key="{{ lookup('file', '/tmp/id_{{master_ip}}_{{user}}.pub') }}"